export type Facility = {
  id?: string;
  name: string;
  menu: string;
  price: string;
  menu2?: string;
  price2?: string;
  menu3?: string;
  price3?: string;
  menu4?: string;
  price4?: string;
  menu5?: string;
  price5?: string;
  explanation?: string;
  prefecture?: string;
  address?: string;
  phone_number?: string;
  created_at?: string;
  facility_id?: string | string[];
  auth_id?: string;
  image_url?: string;
  total_rating_ave?: number;
};
